# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2026-03-13 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS product_stats (
                id INT PRIMARY KEY DEFAULT 1,
                avg_price NUMERIC
            );

            INSERT INTO product_stats (id, avg_price)
            SELECT 1, AVG(price) FROM core_product
            ON CONFLICT (id) DO NOTHING;

            CREATE OR REPLACE FUNCTION recalc_product_stats()
            RETURNS TRIGGER AS $$
            BEGIN
                UPDATE product_stats
                SET avg_price = (SELECT AVG(price) FROM core_product)
                WHERE id = 1;
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS product_stats_update ON core_product;

            CREATE TRIGGER product_stats_update
            AFTER INSERT OR UPDATE OR DELETE ON core_product
            FOR EACH STATEMENT
            EXECUTE PROCEDURE recalc_product_stats();

            CREATE OR REPLACE FUNCTION update_final_price()
            RETURNS TRIGGER AS $$
            DECLARE
                avg_price NUMERIC;
                min_allowed NUMERIC;
                discounted NUMERIC;
            BEGIN
                SELECT product_stats.avg_price
                INTO avg_price
                FROM product_stats
                WHERE id = 1;

                min_allowed := avg_price * 0.5;
                discounted := NEW.price * (1 - NEW.discount / 100);

                NEW.final_price := GREATEST(discounted, min_allowed);

                IF NEW.final_price > NEW.price THEN
                    NEW.final_price := NEW.price;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;



            DROP TRIGGER IF EXISTS trg_update_final_price ON core_product;

            CREATE TRIGGER trg_update_final_price
            BEFORE INSERT OR UPDATE OF price, discount ON core_product
            FOR EACH ROW
            EXECUTE PROCEDURE update_final_price();
            """,

            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_update_final_price ON core_product;
            DROP FUNCTION IF EXISTS update_final_price();

            DROP TRIGGER IF EXISTS product_stats_update ON core_product;
            DROP FUNCTION IF EXISTS recalc_product_stats();

            DROP TABLE IF EXISTS product_stats;
            """
        )

    ]
