# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2026-03-13 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
                migrations.RunSQL(
                    sql="""
                    CREATE OR REPLACE FUNCTION update_final_price()
                    RETURNS TRIGGER AS $$
                    DECLARE
                        avg_price NUMERIC(10,2);
                        threshold NUMERIC(10,2);
                        discounted NUMERIC(10,2);
                        base NUMERIC(10,2);
                    BEGIN
                        SELECT AVG(price) INTO avg_price FROM core_product;

                        threshold := avg_price * 0.5;
                        discounted := NEW.price * (1 - NEW.discount / 100);

                        base := GREATEST(discounted, threshold);

                        NEW.final_price := LEAST(base, NEW.price);

                        RETURN NEW;
                    END;
                    $$ LANGUAGE plpgsql;

                    DROP TRIGGER IF EXISTS trg_update_final_price ON core_product;

                    CREATE TRIGGER trg_update_final_price
                    BEFORE INSERT OR UPDATE ON core_product
                    FOR EACH ROW
                    EXECUTE FUNCTION update_final_price();
                    """,
                    reverse_sql="""
                    DROP TRIGGER IF EXISTS trg_update_final_price ON core_product;
                    DROP FUNCTION IF EXISTS update_final_price();
                    """
            )
    ]
