# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2026-03-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models

import core.models.manufacturers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_importtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(max_length=20, validators=[core.models.manufacturers.validate_phone], verbose_name='Телефон'),
        ),
    ]
